/*
 * This file is generated by jOOQ.
*/
package com.ccbcfx.learn.tables.records;


import com.ccbcfx.learn.tables.Staff;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StaffRecord extends UpdatableRecordImpl<StaffRecord> implements Record15<UInteger, String, LocalDateTime, String, Integer, String, Integer, String, Integer, String, LocalDateTime, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 357881840;

    /**
     * Setter for <code>learn.staff.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>learn.staff.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>learn.staff.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>learn.staff.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>learn.staff.birthday</code>.
     */
    public void setBirthday(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>learn.staff.birthday</code>.
     */
    public LocalDateTime getBirthday() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>learn.staff.phone</code>.
     */
    public void setPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>learn.staff.phone</code>.
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>learn.staff.gender</code>.
     */
    public void setGender(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>learn.staff.gender</code>.
     */
    public Integer getGender() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>learn.staff.img_url</code>. 头像
     */
    public void setImgUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>learn.staff.img_url</code>. 头像
     */
    public String getImgUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>learn.staff.document_type</code>. 证件类型
     */
    public void setDocumentType(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>learn.staff.document_type</code>. 证件类型
     */
    public Integer getDocumentType() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>learn.staff.document_number</code>. 证件号
     */
    public void setDocumentNumber(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>learn.staff.document_number</code>. 证件号
     */
    public String getDocumentNumber() {
        return (String) get(7);
    }

    /**
     * Setter for <code>learn.staff.status</code>.
     */
    public void setStatus(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>learn.staff.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>learn.staff.create_by</code>. 创建人
     */
    public void setCreateBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>learn.staff.create_by</code>. 创建人
     */
    public String getCreateBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>learn.staff.create_at</code>.
     */
    public void setCreateAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>learn.staff.create_at</code>.
     */
    public LocalDateTime getCreateAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>learn.staff.update_by</code>. 修改人
     */
    public void setUpdateBy(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>learn.staff.update_by</code>. 修改人
     */
    public String getUpdateBy() {
        return (String) get(11);
    }

    /**
     * Setter for <code>learn.staff.update_at</code>.
     */
    public void setUpdateAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>learn.staff.update_at</code>.
     */
    public LocalDateTime getUpdateAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>learn.staff.delete_by</code>. 删除人
     */
    public void setDeleteBy(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>learn.staff.delete_by</code>. 删除人
     */
    public String getDeleteBy() {
        return (String) get(13);
    }

    /**
     * Setter for <code>learn.staff.delete_at</code>.
     */
    public void setDeleteAt(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>learn.staff.delete_at</code>.
     */
    public LocalDateTime getDeleteAt() {
        return (LocalDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<UInteger, String, LocalDateTime, String, Integer, String, Integer, String, Integer, String, LocalDateTime, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<UInteger, String, LocalDateTime, String, Integer, String, Integer, String, Integer, String, LocalDateTime, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Staff.STAFF.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Staff.STAFF.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field3() {
        return Staff.STAFF.BIRTHDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Staff.STAFF.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Staff.STAFF.GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Staff.STAFF.IMG_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Staff.STAFF.DOCUMENT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Staff.STAFF.DOCUMENT_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Staff.STAFF.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Staff.STAFF.CREATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field11() {
        return Staff.STAFF.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Staff.STAFF.UPDATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field13() {
        return Staff.STAFF.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Staff.STAFF.DELETE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field15() {
        return Staff.STAFF.DELETE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value3() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getImgUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getDocumentType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getDocumentNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value11() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value13() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getDeleteBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value15() {
        return getDeleteAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value3(LocalDateTime value) {
        setBirthday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value4(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value5(Integer value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value6(String value) {
        setImgUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value7(Integer value) {
        setDocumentType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value8(String value) {
        setDocumentNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value9(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value10(String value) {
        setCreateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value11(LocalDateTime value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value12(String value) {
        setUpdateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value13(LocalDateTime value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value14(String value) {
        setDeleteBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value15(LocalDateTime value) {
        setDeleteAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord values(UInteger value1, String value2, LocalDateTime value3, String value4, Integer value5, String value6, Integer value7, String value8, Integer value9, String value10, LocalDateTime value11, String value12, LocalDateTime value13, String value14, LocalDateTime value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StaffRecord
     */
    public StaffRecord() {
        super(Staff.STAFF);
    }

    /**
     * Create a detached, initialised StaffRecord
     */
    public StaffRecord(UInteger id, String name, LocalDateTime birthday, String phone, Integer gender, String imgUrl, Integer documentType, String documentNumber, Integer status, String createBy, LocalDateTime createAt, String updateBy, LocalDateTime updateAt, String deleteBy, LocalDateTime deleteAt) {
        super(Staff.STAFF);

        set(0, id);
        set(1, name);
        set(2, birthday);
        set(3, phone);
        set(4, gender);
        set(5, imgUrl);
        set(6, documentType);
        set(7, documentNumber);
        set(8, status);
        set(9, createBy);
        set(10, createAt);
        set(11, updateBy);
        set(12, updateAt);
        set(13, deleteBy);
        set(14, deleteAt);
    }
}
