/*
 * This file is generated by jOOQ.
*/
package com.ccbcfx.learn;


import com.ccbcfx.learn.tables.SchemaVersion;
import com.ccbcfx.learn.tables.Staff;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in learn
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>learn.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = com.ccbcfx.learn.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>learn.staff</code>.
     */
    public static final Staff STAFF = com.ccbcfx.learn.tables.Staff.STAFF;
}
