/*
 * This file is generated by jOOQ.
*/
package com.ccbcfx.learn.tables.daos;


import com.ccbcfx.learn.tables.Staff;
import com.ccbcfx.learn.tables.records.StaffRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StaffDao extends DAOImpl<StaffRecord, com.ccbcfx.learn.tables.pojos.Staff, UInteger> {

    /**
     * Create a new StaffDao without any configuration
     */
    public StaffDao() {
        super(Staff.STAFF, com.ccbcfx.learn.tables.pojos.Staff.class);
    }

    /**
     * Create a new StaffDao with an attached configuration
     */
    public StaffDao(Configuration configuration) {
        super(Staff.STAFF, com.ccbcfx.learn.tables.pojos.Staff.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(com.ccbcfx.learn.tables.pojos.Staff object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.ccbcfx.learn.tables.pojos.Staff> fetchById(UInteger... values) {
        return fetch(Staff.STAFF.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.ccbcfx.learn.tables.pojos.Staff fetchOneById(UInteger value) {
        return fetchOne(Staff.STAFF.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.ccbcfx.learn.tables.pojos.Staff> fetchByName(String... values) {
        return fetch(Staff.STAFF.NAME, values);
    }

    /**
     * Fetch records that have <code>birthday IN (values)</code>
     */
    public List<com.ccbcfx.learn.tables.pojos.Staff> fetchByBirthday(LocalDateTime... values) {
        return fetch(Staff.STAFF.BIRTHDAY, values);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<com.ccbcfx.learn.tables.pojos.Staff> fetchByPhone(String... values) {
        return fetch(Staff.STAFF.PHONE, values);
    }

    /**
     * Fetch records that have <code>gender IN (values)</code>
     */
    public List<com.ccbcfx.learn.tables.pojos.Staff> fetchByGender(Integer... values) {
        return fetch(Staff.STAFF.GENDER, values);
    }

    /**
     * Fetch records that have <code>img_url IN (values)</code>
     */
    public List<com.ccbcfx.learn.tables.pojos.Staff> fetchByImgUrl(String... values) {
        return fetch(Staff.STAFF.IMG_URL, values);
    }

    /**
     * Fetch records that have <code>document_type IN (values)</code>
     */
    public List<com.ccbcfx.learn.tables.pojos.Staff> fetchByDocumentType(Integer... values) {
        return fetch(Staff.STAFF.DOCUMENT_TYPE, values);
    }

    /**
     * Fetch records that have <code>document_number IN (values)</code>
     */
    public List<com.ccbcfx.learn.tables.pojos.Staff> fetchByDocumentNumber(String... values) {
        return fetch(Staff.STAFF.DOCUMENT_NUMBER, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.ccbcfx.learn.tables.pojos.Staff> fetchByStatus(Integer... values) {
        return fetch(Staff.STAFF.STATUS, values);
    }

    /**
     * Fetch records that have <code>create_by IN (values)</code>
     */
    public List<com.ccbcfx.learn.tables.pojos.Staff> fetchByCreateBy(String... values) {
        return fetch(Staff.STAFF.CREATE_BY, values);
    }

    /**
     * Fetch records that have <code>create_at IN (values)</code>
     */
    public List<com.ccbcfx.learn.tables.pojos.Staff> fetchByCreateAt(LocalDateTime... values) {
        return fetch(Staff.STAFF.CREATE_AT, values);
    }

    /**
     * Fetch records that have <code>update_by IN (values)</code>
     */
    public List<com.ccbcfx.learn.tables.pojos.Staff> fetchByUpdateBy(String... values) {
        return fetch(Staff.STAFF.UPDATE_BY, values);
    }

    /**
     * Fetch records that have <code>update_at IN (values)</code>
     */
    public List<com.ccbcfx.learn.tables.pojos.Staff> fetchByUpdateAt(LocalDateTime... values) {
        return fetch(Staff.STAFF.UPDATE_AT, values);
    }

    /**
     * Fetch records that have <code>delete_by IN (values)</code>
     */
    public List<com.ccbcfx.learn.tables.pojos.Staff> fetchByDeleteBy(String... values) {
        return fetch(Staff.STAFF.DELETE_BY, values);
    }

    /**
     * Fetch records that have <code>delete_at IN (values)</code>
     */
    public List<com.ccbcfx.learn.tables.pojos.Staff> fetchByDeleteAt(LocalDateTime... values) {
        return fetch(Staff.STAFF.DELETE_AT, values);
    }
}
